# prometheus/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    project: healthcheck-sentinel
    env: development

rule_files:
  - "rules/alerts.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Monitoring Agent with Prometheus metrics
  - job_name: monitoring-agent
    static_configs:
      - targets: ["monitoring-agent:9100"]
